### ISSUE TITLE
[Bug] v1.4 - Button turns into other elements

### ISSUE THREAD

**Issue by GreenComfyTea** [BoltManGuy/MHR-InGame-ModMenu-API#1]
**Problem:**
When there is a button that shows/hides other elements, it sometimes turns into something else, like Options.

+ Going back to Mod List and then opening the mod menu with that button adds yellow Open Menu to it.
+ Sometimes when toggling options that where shown by pressing the button, all toggles get hidden again.

[Video](https://imgur.com/a/Toou2Fe)

PS. The problem with incorrect 'changed' value is fixed btw.

**Comment by Bolt-Scripts** [comment]
Ah, so turns out the cursor index on the scroll list is relative to the scroll index.
You'll notice this happens only when you scroll the menu down a bit such that the button is not on the same line as it was initially.
That is an issue.
Should be a simple fix though

**Comment by Bolt-Scripts** [comment]
Turns out while its a simple to fix that, there were other unnoticed issues with cursor scroll position.
I got it to select all the right stuff, but getting it to actually scroll the list was a completely different story.
Turns out need to intercept and overwrite the scroll index when the game sets the list after I refresh it, simply setting all the values and calling the update cursor function doesnt do that part despite doing everything else. 
Then on top of all that, for some reason setting the cursor pos through code doesnt update the tooltips and keeps trying to display the save game message and had to figure out all the workarounds to override that. Never noticed it before because was using mouse which auto selects.
This UI system is my arch nemesis.

Anyway, all of this should be fixed now
