### ISSUE TITLE
[Bug] "Open Menu" in the wrong place

### ISSUE THREAD

**Issue by GreenComfyTea** [BoltManGuy/MHR-InGame-ModMenu-API#5]
**Describe the bug**
After launching the game, logging in and opening my mod UI, I have "Open Menu" in the last element instead of Options. Resetting scripts fixes the issue.

**Video**
[https://drive.google.com/file/d/1jkBehsN_Vs44ZN5KMgTDIorMFKqNdqmt/view?usp=sharing](https://drive.google.com/file/d/1jkBehsN_Vs44ZN5KMgTDIorMFKqNdqmt/view?usp=sharing)

**Link**
[The mod if can't replicate.](https://github.com/GreenComfyTea/MHR-Forced-Display-Mode-and-Resolution)

**Comment by Bolt-Scripts** [comment]
This seems related to the other issue of the callback being run immediately initially, which is why its fixed if you reset scripts in game.
Like I imagine youre getting the resolutions from the game before it's initialized them and somehow causing an issue with that.
Not entirely sure how that ends up displaying the open menu text instead, but I think it's probably because usually when you have empty or null GUID things for the menu it just somehow displays some default or previous thing.

Anyway, if I run your script without the initialization fix, it replicates this, but if I run it with the fix, it's fine.
So in fact, all these issues were linked all along. And they would've gotten away with it too if it weren't for the meddling GreenComfyTea

Should be fixed in bcb27793c0923f2884e60fd75dbb08183ee20d7f

**Comment by GreenComfyTea** [comment]
Sorry for being meddling and thanks for your trouble xD

**Comment by Bolt-Scripts** [comment]
It's all good, thanks for stressing the system so can fix all the dumb issues 😗
